ruby '~> 3.2.0'
source 'https://rubygems.org'

gem 'actionview'
gem 'fuzzy-string-match', '~> 1.0', '>= 1.0.1'
gem 'interactor'
gem 'launchy'
gem 'packetgen'
gem 'pdf-reader', '~> 1.4'
gem 'puppeteer-ruby'
gem 'rake'
gem 'selenium-webdriver'
