ruby '~> 3.2.0'
source 'https://rubygems.org'

gem 'actionview'
gem 'interactor'
gem 'launchy'
gem 'packetgen'
gem 'pdf-reader', '~> 1.4'
gem 'puppeteer-ruby'
gem 'rake'
gem 'selenium-webdriver', '~> 4.12.0'
